version: 0.2

env:
  parameter-store:
    INFRA_BACKEND_BUCKET: "BACKEND_BUCKET"
    # INFRA_ARTIFACTS_DYNAMODB_TABLE: "DYNAMODB_TABLE"
    INFRA_ARTIFACTS_DYNAMODB_TABLE_ARN: "DYNAMODB_TABLE_ARN"
    
phases:
  install:
    commands:
      # install terraform binary
      - echo "Installing Terraform..."
      - wget -O - https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
      - apt update && apt install terraform
    finally:
      - terraform --version
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - cd ./terraform/Infra/
      - terraform init
    finally:
      - echo Pre Build stage execution complete
  build:
    commands:
      - echo Implementing terraform changes for project - $DESTINATION_PROJECT_NAME.
      - AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - terraform $TERRAFORM_ACTION -auto-approve -var "destination_account_id=$DESTINATION_AWS_ACCOUNT_ID" -var "development_aws_account_id=$DESTINATION_AWS_ACCOUNT_ID" -var "source_account_id=$AWS_ACCOUNT_ID" -var "certificate_id=$CERTIFICATE_ID" -var "image_tag=$IMAGE_TAG" -var "sandbox_aws_account_id=$SANDBOX_AWS_ACCOUNT_ID"
    finally:
      - echo Build step completed.
  post_build:
    commands:
      - echo Entered the post_build phase...
