api_name                      = "ngem-api-dev-ecs-cluster"
region                        = "us-east-1"
private_subnet_tag_key_name   = "type"
private_subnet_tag_value_name = "private"
public_subnet_tag_key_name    = "type"
public_subnet_tag_value_name  = "public"
destination_account_id = ""
security_group = "value"
